### ISSUE TITLE
#10 create the comments table migration

### ISSUE THREAD

**Issue by Juninhoz** [Juninhoz/councilman-management#10]
The projects can be commented by users, before that there will be a table that will record these comments.

1. Create the migration for comments
2. This table must have this fields
  - comment -> string
  - user_id -> belongs_to user
  - project_id -> belongs_to project
  - timestamps

**Comment by Elisangelamsilva** [comment]
hi @Juninhoz , can i do this task?

**Comment by Juninhoz** [comment]
hi @Elisangelamsilva , yes
