### ISSUE TITLE
#3 Add and configure devise to project

### ISSUE THREAD

**Issue by Juninhoz** [Juninhoz/councilman-management#3]
1. Add the gem **devise** to project
2. Configure this gem, mainly on existing controllers
3. Create a migration for users
3. Create a simple view for login.

- [Link for help to add devise gem](https://www.maujor.com/railsgirlsguide/devise.php)

**Comment by ayslanmarcelino** [comment]
can i get this issue?

**Comment by Juninhoz** [comment]
> can i get this issue?

yeaah
