### ISSUE TITLE
#8 Add and configure rubocop gem

### ISSUE THREAD

**Issue by Juninhoz** [Juninhoz/councilman-management#8]
1. Add the **rubocop** gem on project
2. Make a rubocop config file with common cops
- [Link to help this task](https://docs.rubocop.org/rubocop/configuration.html)

**Comment by Elisangelamsilva** [comment]
Hi, @Juninhoz can i do this task?

**Comment by Juninhoz** [comment]
> Hi, @Juninhoz can i do this task?

@Elisangelamsilva , feel free to do this task! :smile:
